# (PART) Blogs

# Equity in AI

Dillon Sparks

Picture this: After a long day of work, you get home and are too exhausted to even open the fridge, let alone cook yourself dinner and clean up afterwards. You decide to open up your favorite food delivery app instead. There are tons of personally recommended restaurants at your fingertips, with suggestions for all of your favorite foods. You pick a new place and decide to order one of the recommended dishes. Crisis averted: you can sink into the couch and watch Netflix until your food comes. 

As technology advances, we are able to “leverage computers and machines to mimic the problem-solving and decision-making capabilities of the human mind.” (IBM Cloud Education, What is Artificial Intelligence (AI)?) This is known as artificial intelligence,  or AI, and it is at the heart of various technological tools that we use every single day. For example, some of the most common real-world applications of AI are speech recognition, customer service, facial recognition/face ID, recommendation engines, automated stock trading, and fraud detection. We interact with and benefit from these technologies more often than we might think. In the beginning scenario, the food delivery app used AI to recommend the dish that you ordered, monitor the transaction for potential fraud during checkout, and to chat with you in the unfortunate event that there were any issues with your order. This is a small example of the ways that companies like Microsoft, Google, Amazon, and IBM, to name a few, utilize AI to enhance consumer experience, while we can simultaneously interact with AI to make life much more convenient. 

However, we must remember that the machine learning algorithms at the heart of artificial intelligence are developed by humans, with their own implicit biases and inherent perspectives of the world. Oftentimes developers are approaching real world issues solely with efficiency in mind, completely ignoring the social justice implications of their algorithms. Additionally, the aforementioned companies and many others like them are seeking profit above all else, which means these powerful tools quickly gain the ability to cause great harm. 

There are numerous instances of discrimination in AI, providing evidence that these powerful technological tools inherit the implicit biases of those developing them. For example, AI used for consumer-lending applications and advertising homes to potential tenants/owners have been found to discriminate against lenders and applicants based on their race. In 2016, Facebook received backlash for its microtargeting feature that “lets advertisers send ads to specific groups via a drop-down menu of categories, including age, race, marital status, and disability status.” (Sisson, P., Housing discrimination goes high tech.) Reporters from ProPublica were able to demonstrate how dangerous this feature is by purchasing ads on the social media website, which blatantly discriminated against people on the basis of race and other demographics, effectively violating the Fair Housing Act. A study from U.C. Berkeley on discrimination in AI influenced consumer-lending found that, “lenders charge otherwise-equivalent Latinx/African-American borrowers 7.9 (3.6) bps higher rates for purchase (refinance) mortgages, costing $765M yearly.” (Bartlett, R., Morse, A., Stanton, R., & Wallace, N. (2019). (rep.). Consumer-Lending Discrimination in the FinTech Era.)

The problem of racism and discrimination in AI is so widespread that SNL even created a skit about it earlier this year. The scene focuses on an ad for a new Amazon Go store, where customers don’t have to pay directly for the items they purchase because their Amazon account will be billed later on. The narrator for the commercial says that Amazon is using “computer vision, deep learning algorithms, and sensor fusion” (“Amazon Go”, SNL. ) to handle transactions. The Black customers in the store are hesitant to even pick anything up because they are afraid that all this ‘cutting edge’ technology will still unfairly target them, and accuse them of stealing. The point of the skit is to dramatize Black people’s distrust of new developments in technology, like a grab and go store, because technology will always have the capacity to reflect the biases of the people developing it, despite how forward it may seem. There are endless other examples of racism and discrimination in applications of AI, including but not limited to hiring technologies, facial recognition, and crime prediction software. 

The call for equitable AI has grown stronger as its uses, and misuses, have become more widespread. There are some companies that have taken it upon themselves to serve the populations that are often the victims of biased algorithms. For example, professionals in the healthcare industry have started using AI to keep patients of all races engaged in their medical plans, treat and avoid opioid abuse, increase vaccine equity, and eliminate bias in diagnosis and treatment (Natarajan, P., Increasing access and equity in healthcare through ai). All of these approaches center the wellbeing of the populations being served, which effectively works to eliminate potential bias in the data and those interpreting it. 

As you can see, this technology is extremely powerful and has the capacity to significantly improve the quality of life for everyone, if used correctly. As Columbia data scientists who pledge to be “Engineers for Good”, it is important that we enter the workforce with equity at the forefront of our efforts. 





Sources Cited:

Akselrod, O. (2021, July 13). How artificial intelligence can deepen racial and economic inequities: News & commentary. American Civil Liberties Union. Retrieved November 14, 2022, from https://www.aclu.org/news/privacy-technology/how-artificial-intelligence-can-deepen-racial-and-economic-inequities 

Amazon Go. (2022). Amazon Go- SNL. Retrieved November 14, 2022, from https://www.youtube.com/watch?v=zS9U3Gc832Y. 

Bartlett, R., Morse, A., Stanton, R., & Wallace, N. (2019). (rep.). Consumer-Lending Discrimination in the FinTech Era. U.C. Berkeley. Retrieved from https://faculty.haas.berkeley.edu/morse/research/papers/discrim.pdf. 

Duggan, W. (2022, November 11). Artificial Intelligence Stocks: The 10 best AI companies. US NEWS. Retrieved November 14, 2022, from https://money.usnews.com/investing/stock-market-news/slideshows/artificial-intelligence-stocks-the-10-best-ai-companies 

Natarajan, P. (2022, April 13). Increasing access and equity in healthcare through ai. MedCity News. Retrieved November 14, 2022, from https://medcitynews.com/2022/04/increasing-access-and-equity-in-healthcare-through-ai/#:~:text=Augmenting%20existing%20human%2Dbased%20practices,a%20diagnosis%20or%20treatment%20plan 

IBM Cloud Education. (2020, June 3). What is Artificial Intelligence (AI)? IBM. Retrieved November 14, 2022, from https://www.ibm.com/cloud/learn/what-is-artificial-intelligence#toc-artificial-7ZT8FnXd 

Rieke, A., Janardan, U., Duarte, N., & Hsu, M. (2021, July 6). Essential work. Upturn. Retrieved November 14, 2022, from https://www.upturn.org/work/essential-work/ 
Sisson, P. (2019, December 17). Housing discrimination goes high tech. Curbed. Retrieved November 14, 2022, from https://archive.curbed.com/2019/12/17/21026311/mortgage-apartment-housing-algorithm-discrimination 






