# Data science internship search survival guide

Austin Chen and Kelly Du

As a current graduate student (and even as an undergraduate), I always knew the importance of gaining real world experience, to translate classroom teachings to something tangible and to understand the field that I will likely be investing the better part of my career towards.  However, the process to obtain this valuable experience and to procure a summer internship is not always easy, in fact, it is actually quite the contrary.  In my personal experience, despite knowing that there are a plethora of positions available, I still struggle to find the actual application forms and links.  And even after applying to numerous positions (and thankfully getting past a few resume screenings), I found that I had no idea what to expect for the different kinds of interviews I would be facing.  Although there are certainly some “interview preparation” resources available online, I often find them to be too generalized, and frankly unhelpful.  Therefore, this Community Contribution project will pool together the actual experiences of two Data Science students, and will hopefully save some of my fellow peers the pain and anguish I felt when I first started my “internship grind”.  

Throughout the composition of this “survival guide”, I was genuinely surprised by the amount of useful information that we were able to put into words .  Despite using the majority of what I included on a daily basis (as the Summer 2023 cycle is still ongoing), actually translating the knowledge on pen and paper made me realize how complicated the interview process can be.  Thus, to evaluate our own project, I can confidently say that the work we accomplished will help others in at least getting familiarized with the data science internship search.  It certainly will not guarantee an interview, or even explicitly increase the rate of success, but it definitely will equip new candidates with a toolbelt for utilization.  If I had to point out something that we might do differently next time, I would include a section of our actual interview processes (with the company name, how many rounds, interview type …etc).  Although the list is not going to be extraordinarily long (but it will be respectable), it will act as a reference for those in need of it.  To conclude, the internship search, especially in the current economic climate, is undoubtedly frustrating and time consuming, but we hope this project will ease some of the stress off of future data science interns. 

Here is the link to our survival guide!
https://github.com/austinchen11/Fall2022_EDAV_Community_Contribution 
