<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 22 Data cleaning with r | Community Contributions for EDAV Fall 2022 Tues/Thurs</title>
<meta name="description" content="Jinchen Liu and Yudu Chen #install.packages(openintro) library(openintro) #install.packages('dplyr') library(dplyr) #install.packages('tidyr') library(tidyr) #install.packages(imputeTS)...">
<meta name="generator" content="bookdown 0.30 with bs4_book()">
<meta property="og:title" content="Chapter 22 Data cleaning with r | Community Contributions for EDAV Fall 2022 Tues/Thurs">
<meta property="og:type" content="book">
<meta property="og:description" content="Jinchen Liu and Yudu Chen #install.packages(openintro) library(openintro) #install.packages('dplyr') library(dplyr) #install.packages('tidyr') library(tidyr) #install.packages(imputeTS)...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 22 Data cleaning with r | Community Contributions for EDAV Fall 2022 Tues/Thurs">
<meta name="twitter:description" content="Jinchen Liu and Yudu Chen #install.packages(openintro) library(openintro) #install.packages('dplyr') library(dplyr) #install.packages('tidyr') library(tidyr) #install.packages(imputeTS)...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.4.1/transition.js"></script><script src="libs/bs3compat-0.4.1/tabs.js"></script><script src="libs/bs3compat-0.4.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><script src="libs/plotly-binding-4.10.1/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script><link href="libs/visjs-7.4.9/vis-timeline-graph2d.min.css" rel="stylesheet">
<script src="libs/visjs-7.4.9/vis-timeline-graph2d.min.js"></script><link href="libs/timeline-0.4/timevis.css" rel="stylesheet">
<script src="libs/timevis-binding-2.1.0/timevis.js"></script><link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="libs/leaflet-1.3.1/leaflet.js"></script><link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="libs/proj4-2.6.2/proj4.min.js"></script><script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script><link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="libs/leaflet-binding-2.1.1/leaflet.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Community Contributions for EDAV Fall 2022 Tues/Thurs</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Welcome!</a></li>
<li><a class="" href="community-contribution.html"><span class="header-section-number">2</span> Community Contribution</a></li>
<li><a class="" href="github-submission-instructions.html"><span class="header-section-number">3</span> GitHub submission instructions</a></li>
<li><a class="" href="sample-project.html"><span class="header-section-number">4</span> Sample project</a></li>
<li class="book-part">Cheatsheets</li>
<li><a class="" href="r-window-functions-cheatsheet.html"><span class="header-section-number">6</span> R window functions cheatsheet</a></li>
<li><a class="" href="rmd-chunk-option-cheat-sheet.html"><span class="header-section-number">7</span> Rmd chunk option cheat sheet</a></li>
<li><a class="" href="helpful-ggplot2-extensions-cheatsheet.html"><span class="header-section-number">8</span> Helpful ggplot2 Extensions Cheatsheet</a></li>
<li><a class="" href="commonly-used-graph-cheatcheet.html"><span class="header-section-number">9</span> Commonly-used graph cheatcheet</a></li>
<li><a class="" href="git-and-version-control.html"><span class="header-section-number">10</span> Git and version control</a></li>
<li><a class="" href="useful-plots-for-bioinfomatics-in-r.html"><span class="header-section-number">11</span> Useful plots for Bioinfomatics in R</a></li>
<li><a class="" href="different-ways-to-create-world-map-in-r.html"><span class="header-section-number">12</span> Different ways to create world map in R</a></li>
<li><a class="" href="color-in-r-python-and-jshtmlcss.html"><span class="header-section-number">13</span> Color in R, Python, and JS/HTML/CSS</a></li>
<li><a class="" href="color-palettes-for-data-visualization.html"><span class="header-section-number">14</span> Color Palettes for Data Visualization</a></li>
<li><a class="" href="data-visualization-using-seaborn.html"><span class="header-section-number">15</span> Data visualization using Seaborn</a></li>
<li><a class="" href="machine-learning-cheatsheet-for-r-and-python.html"><span class="header-section-number">16</span> Machine Learning Cheatsheet for R and Python</a></li>
<li class="book-part">Tutorials</li>
<li><a class="" href="preprocessing-and-visualization-of-time-series-data.html"><span class="header-section-number">18</span> Preprocessing and Visualization of Time Series Data</a></li>
<li><a class="" href="how-to-use-sqldf.html"><span class="header-section-number">19</span> How to use sqldf</a></li>
<li><a class="" href="googlevis-in-r.html"><span class="header-section-number">20</span> googleVis in R</a></li>
<li><a class="" href="tutorial-for-vector-fields-in-r.html"><span class="header-section-number">21</span> Tutorial for vector fields in r</a></li>
<li><a class="active" href="data-cleaning-with-r.html"><span class="header-section-number">22</span> Data cleaning with r</a></li>
<li><a class="" href="introduction-to-shiny-web-apps.html"><span class="header-section-number">23</span> Introduction to Shiny Web Apps</a></li>
<li><a class="" href="python-missingno-library-tutorial.html"><span class="header-section-number">24</span> Python missingno library tutorial</a></li>
<li><a class="" href="data-explorer-tutorial-and-automation.html"><span class="header-section-number">25</span> Data Explorer Tutorial and Automation</a></li>
<li><a class="" href="d-visualization-in-r.html"><span class="header-section-number">26</span> 3D Visualization in R</a></li>
<li><a class="" href="visualizing-time-series-data.html"><span class="header-section-number">27</span> Visualizing Time Series Data</a></li>
<li><a class="" href="igraph-in-r.html"><span class="header-section-number">28</span> igraph in r</a></li>
<li><a class="" href="geo-mapping-coordinate-extraction-using-api-calls.html"><span class="header-section-number">29</span> Geo-Mapping Coordinate Extraction Using API Calls</a></li>
<li><a class="" href="edav-garden.html"><span class="header-section-number">30</span> EDAV Garden</a></li>
<li><a class="" href="data-visualization-with-r-ggplot2-vs.-matlab.html"><span class="header-section-number">31</span> Data Visualization with R ggplot2 vs. Matlab</a></li>
<li class="book-part">Interview Prep</li>
<li><a class="" href="ten-interview-questions-and-answers.html"><span class="header-section-number">33</span> Ten interview questions and answers</a></li>
<li><a class="" href="data-science-internship-search-survival-guide.html"><span class="header-section-number">34</span> Data science internship search survival guide</a></li>
<li class="book-part">Case Studies</li>
<li><a class="" href="benford-case-study.html"><span class="header-section-number">36</span> Benford Case Study</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="github-initial-setup.html"><span class="header-section-number">37</span> Github initial setup</a></li>
<li><a class="" href="tutorial-for-pull-request-mergers.html"><span class="header-section-number">38</span> Tutorial for pull request mergers</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/jtr13/cc22tt">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="data-cleaning-with-r" class="section level1" number="22">
<h1>
<span class="header-section-number">22</span> Data cleaning with r<a class="anchor" aria-label="anchor" href="#data-cleaning-with-r"><i class="fas fa-link"></i></a>
</h1>
<p>Jinchen Liu and Yudu Chen</p>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#install.packages(openintro)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://openintrostat.github.io/openintro/">openintro</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#install.packages('dplyr')</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#install.packages('tidyr')</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#install.packages(imputeTS)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/SteffenMoritz/imputeTS">imputeTS</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#install.packages(caret)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/topepo/caret/">caret</a></span><span class="op">)</span></span></code></pre></div>
<div id="data-cleaning-with-r-1" class="section level2" number="22.1">
<h2>
<span class="header-section-number">22.1</span> Data cleaning with R<a class="anchor" aria-label="anchor" href="#data-cleaning-with-r-1"><i class="fas fa-link"></i></a>
</h2>
<p>In the real world, the data sets we are handling are often not data scientists can readily use. They might contain duplicate entries when entries are supposed to be unique. They might contain missing values, which is problematic for tasks such as training predicative modeling. The data features might be at vastly different scale, which both induces instability of float point arithmatics and inaccurate measurement of feature importance in training machine learning model. We will discuss how to use R to clean Data sets where situations above take place.</p>
</div>
<div id="import-data-set" class="section level2" number="22.2">
<h2>
<span class="header-section-number">22.2</span> Import data set<a class="anchor" aria-label="anchor" href="#import-data-set"><i class="fas fa-link"></i></a>
</h2>
<p>We will explore techniques of data cleaning using “Airquality” dataset from base R and duke_forest data set from openintro. The data set is available in baseR and does not require import from outside source.</p>
<div class="sourceCode" id="cb101"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_preProcessing</span> <span class="op">&lt;-</span> <span class="va">airquality</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     41     190  7.4   67     5   1
## 2     36     118  8.0   72     5   2
## 3     12     149 12.6   74     5   3
## 4     18     313 11.5   62     5   4
## 5     NA      NA 14.3   56     5   5
## 6     28      NA 14.9   66     5   6
## 7     23     299  8.6   65     5   7
## 8     19      99 13.8   59     5   8
## 9      8      19 20.1   61     5   9
## 10    NA     194  8.6   69     5  10</code></pre>
<div class="sourceCode" id="cb103"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">duke_forest_copy</span> <span class="op">&lt;-</span> <span class="va">duke_forest</span></span></code></pre></div>
</div>
<div id="introduction" class="section level2" number="22.3">
<h2>
<span class="header-section-number">22.3</span> Introduction<a class="anchor" aria-label="anchor" href="#introduction"><i class="fas fa-link"></i></a>
</h2>
<p>In the real world, the data sets we are handling are often not data scientists can readily use. They might contain duplicate entries when entries are supposed to be unique. They might contain missing values, which is problematic for tasks such as training predicative modeling. The data features might be at vastly different scale, which both induces instability of float point arithmatics and inaccurate measurement of feature importance in training machine learning model. We will discuss how to use R to clean Data sets where situations above take place.</p>
</div>
<div id="data-frame-modification-general-modification" class="section level2" number="22.4">
<h2>
<span class="header-section-number">22.4</span> Data frame modification (general modification)<a class="anchor" aria-label="anchor" href="#data-frame-modification-general-modification"><i class="fas fa-link"></i></a>
</h2>
<p>For the most of the time, we will have to engineer our data sets before we do some data analyzation on them. Here I present some tricks to modify our dat sets in R.</p>
<div id="create-dataframe-by-arrays" class="section level3" number="22.4.1">
<h3>
<span class="header-section-number">22.4.1</span> Create DataFrame by arrays<a class="anchor" aria-label="anchor" href="#create-dataframe-by-arrays"><i class="fas fa-link"></i></a>
</h3>
<p>Creating DataFrame by two arrays, These two arrays will by columns of df.Array length should be the same.order matters.</p>
<div class="sourceCode" id="cb104"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">first_column</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_1"</span>, <span class="st">"value_2"</span>, <span class="st">"value_3"</span><span class="op">)</span></span>
<span><span class="va">second_column</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_4"</span>, <span class="st">"value_5"</span>, <span class="st">"value_6"</span><span class="op">)</span></span>
<span><span class="va">third_column</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_7"</span>, <span class="st">"value_8"</span>, <span class="st">"value_9"</span><span class="op">)</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">first_column</span>, <span class="va">second_column</span><span class="op">)</span></span>
<span><span class="va">df</span></span></code></pre></div>
<pre><code>##   first_column second_column
## 1      value_1       value_4
## 2      value_2       value_5
## 3      value_3       value_6</code></pre>
<p>another way to create dataFrame, both method produce the same result.</p>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span> <span class="op">(</span>first_column  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_1"</span>, <span class="st">"value_2"</span>, <span class="st">"value_3"</span><span class="op">)</span>,</span>
<span>                  second_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_4"</span>, <span class="st">"value_5"</span>, <span class="st">"value_6"</span><span class="op">)</span>,</span>
<span>                  third_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_7"</span>, <span class="st">"value_8"</span>, <span class="st">"value_9"</span><span class="op">)</span></span>
<span>                  <span class="op">)</span></span>
<span><span class="va">df</span></span></code></pre></div>
<pre><code>##   first_column second_column third_column
## 1      value_1       value_4      value_7
## 2      value_2       value_5      value_8
## 3      value_3       value_6      value_9</code></pre>
</div>
<div id="create-dataframe-by-combining-two-dataframeusing-cbindrbind" class="section level3" number="22.4.2">
<h3>
<span class="header-section-number">22.4.2</span> Create DataFrame by combining two dataFrame(using cbind/rbind)<a class="anchor" aria-label="anchor" href="#create-dataframe-by-combining-two-dataframeusing-cbindrbind"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># create a new dataFrame</span></span>
<span><span class="va">df1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span> <span class="op">(</span>first_column  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_1"</span>, <span class="st">"value_2"</span>, <span class="st">"value_3"</span><span class="op">)</span>,</span>
<span>                  second_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_4"</span>, <span class="st">"value_5"</span>, <span class="st">"value_6"</span><span class="op">)</span>,</span>
<span>                  third_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_7"</span>, <span class="st">"value_8"</span>, <span class="st">"value_9"</span><span class="op">)</span></span>
<span>                  <span class="op">)</span></span>
<span><span class="va">df2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span> <span class="op">(</span>third_column  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_7"</span>, <span class="st">"value_8"</span>, <span class="st">"value_9"</span><span class="op">)</span>,</span>
<span>                  fourth_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_10"</span>, <span class="st">"value_11"</span>, <span class="st">"value_12"</span><span class="op">)</span></span>
<span>                  <span class="op">)</span></span></code></pre></div>
<p>combine two dataframe by columns,order matters.</p>
<div class="sourceCode" id="cb109"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">bigger_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">df1</span>, <span class="va">df2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bigger_df</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   first_column second_column third_column third_column fourth_column
## 1      value_1       value_4      value_7      value_7      value_10
## 2      value_2       value_5      value_8      value_8      value_11
## 3      value_3       value_6      value_9      value_9      value_12</code></pre>
<p>combine two dataframe by rows, two DataFrames must have the same column name and order.</p>
<div class="sourceCode" id="cb111"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">df3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span> <span class="op">(</span>third_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_7"</span>, <span class="st">"value_8"</span>, <span class="st">"value_9"</span><span class="op">)</span>,</span>
<span>                  fourth_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"value_10"</span>, <span class="st">"value_11"</span>, <span class="st">"value_12"</span><span class="op">)</span></span>
<span>                  <span class="op">)</span></span>
<span><span class="va">bigger_df2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">df2</span>,<span class="va">df3</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   third_column fourth_column
## 1      value_7      value_10
## 2      value_8      value_11
## 3      value_9      value_12
## 4      value_7      value_10
## 5      value_8      value_11
## 6      value_9      value_12</code></pre>
</div>
<div id="addingchange-row-name" class="section level3" number="22.4.3">
<h3>
<span class="header-section-number">22.4.3</span> adding/change row name<a class="anchor" aria-label="anchor" href="#addingchange-row-name"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb113"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   third_column fourth_column
## 1      value_7      value_10
## 2      value_8      value_11
## 3      value_9      value_12
## 4      value_7      value_10
## 5      value_8      value_11
## 6      value_9      value_12</code></pre>
<div class="sourceCode" id="cb115"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="va">LETTERS</span><span class="op">[</span><span class="fl">16</span><span class="op">:</span><span class="fl">21</span><span class="op">]</span></span>
<span></span>
<span><span class="va">bigger_df2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">bigger_df2</span>,</span>
<span>                   row.names <span class="op">=</span> <span class="va">LETTERS</span><span class="op">[</span><span class="fl">16</span><span class="op">:</span><span class="fl">21</span><span class="op">]</span><span class="op">)</span></span>
<span><span class="co"># both ways produce the same result</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   third_column fourth_column
## P      value_7      value_10
## Q      value_8      value_11
## R      value_9      value_12
## S      value_7      value_10
## T      value_8      value_11
## U      value_9      value_12</code></pre>
<div class="sourceCode" id="cb117"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># rownames can change the row name.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fl">1</span><span class="op">:</span><span class="fl">6</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   third_column fourth_column
## 1      value_7      value_10
## 2      value_8      value_11
## 3      value_9      value_12
## 4      value_7      value_10
## 5      value_8      value_11
## 6      value_9      value_12</code></pre>
<div class="sourceCode" id="cb119"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## get row names</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "1" "2" "3" "4" "5" "6"</code></pre>
</div>
<div id="changing-column-names" class="section level3" number="22.4.4">
<h3>
<span class="header-section-number">22.4.4</span> changing column names<a class="anchor" aria-label="anchor" href="#changing-column-names"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb121"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   first_column second_column third_column
## 1      value_1       value_4      value_7
## 2      value_2       value_5      value_8
## 3      value_3       value_6      value_9</code></pre>
<div class="sourceCode" id="cb123"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># change all column names</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'C1'</span>,<span class="st">'C2'</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span></span></code></pre></div>
<pre><code>##        C1      C2      NA
## 1 value_1 value_4 value_7
## 2 value_2 value_5 value_8
## 3 value_3 value_6 value_9</code></pre>
<div class="sourceCode" id="cb125"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># change specific column name</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'new column name'</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   new column name      C2      NA
## 1         value_1 value_4 value_7
## 2         value_2 value_5 value_8
## 3         value_3 value_6 value_9</code></pre>
<div class="sourceCode" id="cb127"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">#get column names</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "new column name" "C2"              NA</code></pre>
</div>
<div id="adding-array-to-to-dataframe-as-new-column" class="section level3" number="22.4.5">
<h3>
<span class="header-section-number">22.4.5</span> Adding array to to dataFrame as new column<a class="anchor" aria-label="anchor" href="#adding-array-to-to-dataframe-as-new-column"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb129"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bigger_df2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   third_column fourth_column
## 1      value_7      value_10
## 2      value_8      value_11
## 3      value_9      value_12
## 4      value_7      value_10
## 5      value_8      value_11
## 6      value_9      value_12</code></pre>
<div class="sourceCode" id="cb131"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">bigger_df_new</span> <span class="op">=</span> <span class="va">bigger_df2</span></span>
<span></span>
<span><span class="va">bigger_df_new</span><span class="op">$</span><span class="va">new</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">6</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="va">bigger_df_new</span><span class="op">[</span><span class="st">'new'</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">6</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">12</span><span class="op">)</span></span>
<span></span>
<span><span class="va">new</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span>, <span class="fl">6</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">12</span><span class="op">)</span></span>
<span><span class="va">bigger_df_new</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">df</span>, <span class="va">new</span><span class="op">)</span></span>
<span><span class="co"># three ways produce the same result.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">bigger_df_new</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   new column name      C2      NA new
## 1         value_1 value_4 value_7   3
## 2         value_2 value_5 value_8   3
## 3         value_3 value_6 value_9   6
## 4         value_1 value_4 value_7   7
## 5         value_2 value_5 value_8   8
## 6         value_3 value_6 value_9  12</code></pre>
</div>
<div id="adding-column-by-combination-of-other-columns" class="section level3" number="22.4.6">
<h3>
<span class="header-section-number">22.4.6</span> adding column by combination of other columns<a class="anchor" aria-label="anchor" href="#adding-column-by-combination-of-other-columns"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb133"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># using mutate() from dplyr</span></span>
<span><span class="va">df_math</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span> <span class="op">(</span>first_column  <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>                  second_column <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span><span class="op">)</span></span>
<span>                  <span class="op">)</span></span>
<span></span>
<span><span class="co">## add new column as mathematical operation of other columns.</span></span>
<span><span class="va">output</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">df_math</span>,</span>
<span>                 sum <span class="op">=</span> <span class="op">(</span><span class="va">first_column</span> <span class="op">+</span> <span class="va">second_column</span><span class="op">)</span> <span class="op">/</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">output</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   first_column second_column sum
## 1            1             4 2.5
## 2            2             5 3.5
## 3            3             6 4.5</code></pre>
<div class="sourceCode" id="cb135"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## add new column by boolean operation of other columns.</span></span>
<span><span class="va">output</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">df_math</span>,</span>
<span>                 divisible_by2 <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span></span>
<span>                   <span class="va">first_column</span><span class="op"><a href="https://rdrr.io/r/base/Arithmetic.html">%%</a></span><span class="fl">2</span> <span class="op">==</span> <span class="fl">0</span> <span class="op">~</span> <span class="st">"yes"</span>,</span>
<span>                   <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">"No"</span> <span class="co"># otherwise not divisiable by 2.</span></span>
<span>                 <span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">output</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   first_column second_column divisible_by2
## 1            1             4            No
## 2            2             5           yes
## 3            3             6            No</code></pre>
</div>
<div id="joining-two-table-2" class="section level3" number="22.4.7">
<h3>
<span class="header-section-number">22.4.7</span> joining two table <strong>[2]</strong><a class="anchor" aria-label="anchor" href="#joining-two-table-2"><i class="fas fa-link"></i></a>
</h3>
<p>Bewaring that the order of dataframe in the merge function matters(right join left)</p>
<div class="sourceCode" id="cb137"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">emp_df</span><span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  emp_id<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">4</span>,<span class="fl">5</span>,<span class="fl">6</span><span class="op">)</span>,</span>
<span>  name<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Smith"</span>,<span class="st">"Rose"</span>,<span class="st">"Williams"</span>,<span class="st">"Jones"</span>,<span class="st">"Brown"</span>,<span class="st">"Brown"</span><span class="op">)</span>,</span>
<span>  superior_emp_id<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">2</span>,<span class="fl">2</span><span class="op">)</span>,</span>
<span>  dept_id<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>,<span class="fl">20</span>,<span class="fl">10</span>,<span class="fl">10</span>,<span class="fl">40</span>,<span class="fl">50</span><span class="op">)</span>,</span>
<span>  dept_branch_id<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">101</span>,<span class="fl">102</span>,<span class="fl">101</span>,<span class="fl">101</span>,<span class="fl">104</span>,<span class="fl">105</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">dept_df</span><span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  dept_id<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">10</span>,<span class="fl">20</span>,<span class="fl">30</span>,<span class="fl">40</span><span class="op">)</span>,</span>
<span>  dept_name<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Finance"</span>,<span class="st">"Marketing"</span>,<span class="st">"Sales"</span>,<span class="st">"IT"</span><span class="op">)</span>,</span>
<span>  dept_branch_id<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">101</span>,<span class="fl">102</span>,<span class="fl">103</span>,<span class="fl">104</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co"># inner join</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/merge.html">merge</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">emp_df</span>, y <span class="op">=</span> <span class="va">dept_df</span>, by <span class="op">=</span> <span class="st">"dept_id"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   dept_id emp_id     name superior_emp_id dept_branch_id.x dept_name
## 1      10      1    Smith              -1              101   Finance
## 2      10      3 Williams               1              101   Finance
## 3      10      4    Jones               2              101   Finance
## 4      20      2     Rose               1              102 Marketing
## 5      40      5    Brown               2              104        IT
##   dept_branch_id.y
## 1              101
## 2              101
## 3              101
## 4              102
## 5              104</code></pre>
<div class="sourceCode" id="cb139"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># outer join </span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/merge.html">merge</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">emp_df</span>, y <span class="op">=</span> <span class="va">dept_df</span>, by <span class="op">=</span> <span class="st">"dept_id"</span>, all <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="co"># all means containing all rows</span></span></code></pre></div>
<pre><code>##   dept_id emp_id     name superior_emp_id dept_branch_id.x dept_name
## 1      10      1    Smith              -1              101   Finance
## 2      10      3 Williams               1              101   Finance
## 3      10      4    Jones               2              101   Finance
## 4      20      2     Rose               1              102 Marketing
## 5      30     NA     &lt;NA&gt;              NA               NA     Sales
## 6      40      5    Brown               2              104        IT
## 7      50      6    Brown               2              105      &lt;NA&gt;
##   dept_branch_id.y
## 1              101
## 2              101
## 3              101
## 4              102
## 5              103
## 6              104
## 7               NA</code></pre>
<div class="sourceCode" id="cb141"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># left join</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/merge.html">merge</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">emp_df</span>, y <span class="op">=</span> <span class="va">dept_df</span>, by <span class="op">=</span> <span class="st">"dept_id"</span>, all.x <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="co"># all.x means containing all rows in x</span></span></code></pre></div>
<pre><code>##   dept_id emp_id     name superior_emp_id dept_branch_id.x dept_name
## 1      10      1    Smith              -1              101   Finance
## 2      10      3 Williams               1              101   Finance
## 3      10      4    Jones               2              101   Finance
## 4      20      2     Rose               1              102 Marketing
## 5      40      5    Brown               2              104        IT
## 6      50      6    Brown               2              105      &lt;NA&gt;
##   dept_branch_id.y
## 1              101
## 2              101
## 3              101
## 4              102
## 5              104
## 6               NA</code></pre>
<div class="sourceCode" id="cb143"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># right join</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/merge.html">merge</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">emp_df</span>, y <span class="op">=</span> <span class="va">dept_df</span>, by <span class="op">=</span> <span class="st">"dept_id"</span>, all.y <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="co"># all.y means containing all rows in y</span></span></code></pre></div>
<pre><code>##   dept_id emp_id     name superior_emp_id dept_branch_id.x dept_name
## 1      10      1    Smith              -1              101   Finance
## 2      10      3 Williams               1              101   Finance
## 3      10      4    Jones               2              101   Finance
## 4      20      2     Rose               1              102 Marketing
## 5      30     NA     &lt;NA&gt;              NA               NA     Sales
## 6      40      5    Brown               2              104        IT
##   dept_branch_id.y
## 1              101
## 2              101
## 3              101
## 4              102
## 5              103
## 6              104</code></pre>
</div>
<div id="pivoting-dataframe-understanding-pivot_longer" class="section level3" number="22.4.8">
<h3>
<span class="header-section-number">22.4.8</span> pivoting dataframe, understanding pivot_longer<a class="anchor" aria-label="anchor" href="#pivoting-dataframe-understanding-pivot_longer"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># pivot_longer transform a data frame from a wide format to a long format by converting feature names to a categorical feature.</span></span>
<span></span>
<span><span class="co"># pivot_longer is from the package tidyr.</span></span>
<span><span class="va">needs_pivoting</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sticker_type<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'A'</span>, <span class="st">'B'</span>, <span class="st">'C'</span>, <span class="st">'D'</span><span class="op">)</span>,</span>
<span>                 sparrow<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">12</span>, <span class="fl">15</span>, <span class="fl">19</span>, <span class="fl">19</span><span class="op">)</span>,</span>
<span>                 eagle<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">22</span>, <span class="fl">29</span>, <span class="fl">18</span>, <span class="fl">12</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">needs_pivoting</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   sticker_type sparrow eagle
## 1            A      12    22
## 2            B      15    29
## 3            C      19    18
## 4            D      19    12</code></pre>
<div class="sourceCode" id="cb147"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">needs_pivoting</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>cols<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'sparrow'</span>, <span class="st">'eagle'</span><span class="op">)</span>, <span class="co"># the columns(feature names) to be pivoted</span></span>
<span>                                names_to<span class="op">=</span><span class="st">'species'</span>, <span class="co"># the name of the column of features</span></span>
<span>                                values_to<span class="op">=</span><span class="st">'price'</span><span class="op">)</span> <span class="co"># the name of the column of values</span></span></code></pre></div>
<pre><code>## # A tibble: 8 × 3
##   sticker_type species price
##   &lt;chr&gt;        &lt;chr&gt;   &lt;dbl&gt;
## 1 A            sparrow    12
## 2 A            eagle      22
## 3 B            sparrow    15
## 4 B            eagle      29
## 5 C            sparrow    19
## 6 C            eagle      18
## 7 D            sparrow    19
## 8 D            eagle      12</code></pre>
<div id="binning-using-cut" class="section level4" number="22.4.8.1">
<h4>
<span class="header-section-number">22.4.8.1</span> binning using cut()<a class="anchor" aria-label="anchor" href="#binning-using-cut"><i class="fas fa-link"></i></a>
</h4>
<p>This is also a good way to categorize feature</p>
<div class="sourceCode" id="cb149"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hour_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>shop_name<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'MAC'</span>, <span class="st">'Tangro'</span>, <span class="st">'cummington'</span>, <span class="st">'Burger King'</span>, <span class="st">'judgement'</span>, <span class="st">'KFC'</span>, <span class="st">'ye'</span>, <span class="st">'Dungeon'</span>, <span class="st">'Razer'</span>, <span class="st">'yeah sir'</span>, <span class="st">'Koban wife'</span>, <span class="st">'string'</span><span class="op">)</span>,</span>
<span>                 operating_hours<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">7</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">11</span>, <span class="fl">13</span>, <span class="fl">8</span><span class="op">)</span>,</span>
<span>                 rebounds<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>, <span class="fl">7</span>, <span class="fl">4</span>, <span class="fl">6</span>, <span class="fl">3</span>, <span class="fl">8</span>, <span class="fl">9</span>, <span class="fl">9</span>, <span class="fl">12</span>, <span class="fl">11</span>, <span class="fl">8</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">hour_df</span></span></code></pre></div>
<pre><code>##      shop_name operating_hours rebounds
## 1          MAC               2        7
## 2       Tangro               5        7
## 3   cummington               4        4
## 4  Burger King               7        6
## 5    judgement               7        3
## 6          KFC               8        8
## 7           ye               5        9
## 8      Dungeon               4        9
## 9        Razer               5       12
## 10    yeah sir              11       11
## 11  Koban wife              13        8
## 12      string               8        9</code></pre>
<div class="sourceCode" id="cb151"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">new_hour_df</span> <span class="op">&lt;-</span> <span class="va">hour_df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>operating_hours_bin <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">operating_hours</span>, breaks<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">5</span>,<span class="fl">9</span>,<span class="fl">13</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">new_hour_df</span></span></code></pre></div>
<pre><code>##      shop_name operating_hours rebounds operating_hours_bin
## 1          MAC               2        7               (0,5]
## 2       Tangro               5        7               (0,5]
## 3   cummington               4        4               (0,5]
## 4  Burger King               7        6               (5,9]
## 5    judgement               7        3               (5,9]
## 6          KFC               8        8               (5,9]
## 7           ye               5        9               (0,5]
## 8      Dungeon               4        9               (0,5]
## 9        Razer               5       12               (0,5]
## 10    yeah sir              11       11              (9,13]
## 11  Koban wife              13        8              (9,13]
## 12      string               8        9               (5,9]</code></pre>
</div>
<div id="binning-using-case" class="section level4" number="22.4.8.2">
<h4>
<span class="header-section-number">22.4.8.2</span> binning using case()<a class="anchor" aria-label="anchor" href="#binning-using-case"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb153"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hour_df2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>shop_name<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'MAC'</span>, <span class="st">'Tangro'</span>, <span class="st">'cummington'</span>, <span class="st">'Burger King'</span>, <span class="st">'judgement'</span>, <span class="st">'KFC'</span>, <span class="st">'ye'</span>, <span class="st">'Dungeon'</span>, <span class="st">'Razer'</span>, <span class="st">'yeah sir'</span>, <span class="st">'Koban wife'</span>, <span class="st">'string'</span><span class="op">)</span>,</span>
<span>                 operating_hours<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">7</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">5</span>, <span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">11</span>, <span class="fl">13</span>, <span class="fl">8</span><span class="op">)</span>,</span>
<span>                 rebounds<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>, <span class="fl">7</span>, <span class="fl">4</span>, <span class="fl">6</span>, <span class="fl">3</span>, <span class="fl">8</span>, <span class="fl">9</span>, <span class="fl">9</span>, <span class="fl">12</span>, <span class="fl">11</span>, <span class="fl">8</span>, <span class="fl">9</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">hour_df</span></span></code></pre></div>
<pre><code>##      shop_name operating_hours rebounds
## 1          MAC               2        7
## 2       Tangro               5        7
## 3   cummington               4        4
## 4  Burger King               7        6
## 5    judgement               7        3
## 6          KFC               8        8
## 7           ye               5        9
## 8      Dungeon               4        9
## 9        Razer               5       12
## 10    yeah sir              11       11
## 11  Koban wife              13        8
## 12      string               8        9</code></pre>
<div class="sourceCode" id="cb155"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">new_hour_df</span> <span class="op">&lt;-</span> <span class="va">hour_df2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>operating_hours_bin <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span> <span class="co"># logistics</span></span>
<span>                   <span class="va">operating_hours</span> <span class="op">&lt;=</span> <span class="fl">3</span> <span class="op">~</span> <span class="st">'very short'</span>,</span>
<span>                   <span class="va">operating_hours</span> <span class="op">&lt;=</span> <span class="fl">6</span> <span class="op">&amp;</span> <span class="va">operating_hours</span> <span class="op">&gt;</span> <span class="fl">3</span> <span class="op">~</span> <span class="st">'short'</span>,</span>
<span>                   <span class="va">operating_hours</span> <span class="op">&lt;=</span> <span class="fl">10</span> <span class="op">&amp;</span> <span class="va">operating_hours</span> <span class="op">&gt;</span> <span class="fl">6</span> <span class="op">~</span> <span class="st">'median'</span>,</span>
<span>                   <span class="va">operating_hours</span> <span class="op">&gt;</span> <span class="fl">10</span> <span class="op">~</span> <span class="st">'long'</span>,</span>
<span>                   <span class="cn">TRUE</span> <span class="op">~</span> <span class="st">'what else will this be?'</span></span>
<span>                 <span class="op">)</span><span class="op">)</span></span>
<span><span class="va">new_hour_df</span></span></code></pre></div>
<pre><code>##      shop_name operating_hours rebounds operating_hours_bin
## 1          MAC               2        7          very short
## 2       Tangro               5        7               short
## 3   cummington               4        4               short
## 4  Burger King               7        6              median
## 5    judgement               7        3              median
## 6          KFC               8        8              median
## 7           ye               5        9               short
## 8      Dungeon               4        9               short
## 9        Razer               5       12               short
## 10    yeah sir              11       11                long
## 11  Koban wife              13        8                long
## 12      string               8        9              median</code></pre>
</div>
</div>
<div id="ordering" class="section level3" number="22.4.9">
<h3>
<span class="header-section-number">22.4.9</span> ordering<a class="anchor" aria-label="anchor" href="#ordering"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb157"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">student_result_wild</span><span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>name<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Ram"</span>,<span class="st">"Geeta"</span>,<span class="st">"John"</span>,<span class="st">"Paul"</span>,</span>
<span>                                 <span class="st">"Cassie"</span>,<span class="st">"Geeta"</span>,<span class="st">"Paul"</span><span class="op">)</span>,</span>
<span>                          maths<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>,<span class="fl">8</span>,<span class="fl">8</span>,<span class="fl">9</span>,<span class="fl">10</span>,<span class="fl">8</span>,<span class="fl">9</span><span class="op">)</span>,</span>
<span>                          science<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">5</span>,<span class="fl">7</span>,<span class="fl">6</span>,<span class="fl">8</span>,<span class="fl">9</span>,<span class="fl">7</span>,<span class="fl">8</span><span class="op">)</span>,</span>
<span>                          history<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">7</span>,<span class="fl">7</span>,<span class="fl">7</span>,<span class="fl">7</span>,<span class="fl">7</span>,<span class="fl">7</span>,<span class="fl">7</span><span class="op">)</span>,</span>
<span>                          id <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">9</span>,<span class="fl">2</span>,<span class="fl">3</span>,<span class="fl">5</span>,<span class="fl">13</span>,<span class="fl">2</span>,<span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">student_result_wild</span> <span class="co"># data with out ordering</span></span></code></pre></div>
<pre><code>##     name maths science history id
## 1    Ram     7       5       7  9
## 2  Geeta     8       7       7  2
## 3   John     8       6       7  3
## 4   Paul     9       8       7  5
## 5 Cassie    10       9       7 13
## 6  Geeta     8       7       7  2
## 7   Paul     9       8       7  5</code></pre>
<div class="sourceCode" id="cb159"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># order data by certain variable (ascending)</span></span>
<span><span class="va">student_result_wild</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="va">student_result_wild</span><span class="op">$</span><span class="va">id</span><span class="op">)</span>,<span class="op">]</span></span></code></pre></div>
<pre><code>##     name maths science history id
## 2  Geeta     8       7       7  2
## 6  Geeta     8       7       7  2
## 3   John     8       6       7  3
## 4   Paul     9       8       7  5
## 7   Paul     9       8       7  5
## 1    Ram     7       5       7  9
## 5 Cassie    10       9       7 13</code></pre>
<div class="sourceCode" id="cb161"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># order data by certain variable (descending)</span></span>
<span><span class="va">student_result_wild</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="op">-</span><span class="va">student_result_wild</span><span class="op">$</span><span class="va">id</span><span class="op">)</span>,<span class="op">]</span></span></code></pre></div>
<pre><code>##     name maths science history id
## 5 Cassie    10       9       7 13
## 1    Ram     7       5       7  9
## 4   Paul     9       8       7  5
## 7   Paul     9       8       7  5
## 3   John     8       6       7  3
## 2  Geeta     8       7       7  2
## 6  Geeta     8       7       7  2</code></pre>
<div class="sourceCode" id="cb163"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># order data by multiple variable, the second orders the duplicates in first variable</span></span>
<span><span class="va">student_result_wild</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/order.html">order</a></span><span class="op">(</span><span class="op">-</span><span class="va">student_result_wild</span><span class="op">$</span><span class="va">id</span>, <span class="va">student_result_wild</span><span class="op">$</span><span class="va">science</span><span class="op">)</span>,<span class="op">]</span></span></code></pre></div>
<pre><code>##     name maths science history id
## 5 Cassie    10       9       7 13
## 1    Ram     7       5       7  9
## 4   Paul     9       8       7  5
## 7   Paul     9       8       7  5
## 3   John     8       6       7  3
## 2  Geeta     8       7       7  2
## 6  Geeta     8       7       7  2</code></pre>
</div>
</div>
<div id="duplicated-values" class="section level2" number="22.5">
<h2>
<span class="header-section-number">22.5</span> Duplicated Values<a class="anchor" aria-label="anchor" href="#duplicated-values"><i class="fas fa-link"></i></a>
</h2>
<p>In many cases, we observe duplicated values in a data set where every instances are supposed to be unique. We will now discussed how to handle duplicates.</p>
<div id="data-set-with-row-wise-duplicates" class="section level3" number="22.5.1">
<h3>
<span class="header-section-number">22.5.1</span> Data set with row-wise duplicates<a class="anchor" aria-label="anchor" href="#data-set-with-row-wise-duplicates"><i class="fas fa-link"></i></a>
</h3>
<p>Although the dataset we use in this example, airquality data, does not have duplicate, we will use it illustrate the techniques of handling duplicate data.</p>
<div class="sourceCode" id="cb165"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_duplicated_values</span> <span class="op">=</span> <span class="va">airQuality_preProcessing</span></span></code></pre></div>
<p>We see the data frame should have no duplicate rows to begin with.</p>
<div class="sourceCode" id="cb166"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of duplicated rows in the data is '</span>,<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of duplicated rows in the data is 0"</code></pre>
<p>Now we randomly pick 5 instances from the data frame and insert them into the data frame to induce duplication</p>
<div class="sourceCode" id="cb168"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span> <span class="fl">5</span><span class="op">)</span></span>
<span><span class="op">{</span></span>
<span>  <span class="va">data_duplicated_values</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">+</span><span class="fl">1</span>,<span class="op">]</span> <span class="op">=</span> <span class="va">data_duplicated_values</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, min <span class="op">=</span> <span class="fl">1</span>, max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,<span class="op">]</span></span>
<span><span class="op">}</span></span></code></pre></div>
<p>We should now have 5 duplicated instances:</p>
<div class="sourceCode" id="cb169"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of duplicated rows in the data after insertion is '</span>,<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of duplicated rows in the data after insertion is 5"</code></pre>
<p>The “duplicated(df)” returns a boolean array where each value at each index indicates if row at the same index in original data frame is duplicated or not. We can use ’duplicated(df)” to extract duplicated rows:</p>
<div class="sourceCode" id="cb171"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_duplicated_values</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span>,<span class="op">]</span></span></code></pre></div>
<pre><code>##     Ozone Solar.R Wind Temp Month Day
## 154    NA     291 14.9   91     7  14
## 155    36     118  8.0   72     5   2
## 156    50     275  7.4   86     7  29
## 157    NA     264 14.3   79     6   6
## 158   118     225  2.3   94     8  29</code></pre>
<p>By adding “!” before “duplicated(df)”, we can negate logics in “duplicated(df)” and access non duplicate rows as a data frame:</p>
<div class="sourceCode" id="cb173"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span>,<span class="op">]</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     41     190  7.4   67     5   1
## 2     36     118  8.0   72     5   2
## 3     12     149 12.6   74     5   3
## 4     18     313 11.5   62     5   4
## 5     NA      NA 14.3   56     5   5
## 6     28      NA 14.9   66     5   6
## 7     23     299  8.6   65     5   7
## 8     19      99 13.8   59     5   8
## 9      8      19 20.1   61     5   9
## 10    NA     194  8.6   69     5  10</code></pre>
<p>There should be no duplicates</p>
<div class="sourceCode" id="cb175"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'duplicates in data frame formed by unique rows in original data frame is '</span>,<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span>,<span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "duplicates in data frame formed by unique rows in original data frame is 0"</code></pre>
<p>We can create a new reference to the data set with no duplicates. For the purpose of reusing “data_duplicated_values”, I will just assign the new reference to itself:</p>
<div class="sourceCode" id="cb177"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_duplicated_values</span> <span class="op">&lt;-</span> <span class="va">data_duplicated_values</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span>,<span class="op">]</span></span></code></pre></div>
<p>Now “data_duplicated_values” should have no duplicates:</p>
<div class="sourceCode" id="cb178"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of duplicated value after re setting reference is '</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of duplicated value after re setting reference is 0"</code></pre>
<p>Another way is to use “distinct()” function from tidyverse package.</p>
<div class="sourceCode" id="cb180"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span> <span class="fl">5</span><span class="op">)</span></span>
<span><span class="op">{</span></span>
<span>  <span class="va">data_duplicated_values</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">+</span><span class="fl">1</span>,<span class="op">]</span> <span class="op">=</span> <span class="va">data_duplicated_values</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, min <span class="op">=</span> <span class="fl">1</span>, max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>,<span class="op">]</span></span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of duplicate value in data frame before calling distinct is'</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of duplicate value in data frame before calling distinct is5"</code></pre>
<div class="sourceCode" id="cb182"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_duplicated_values</span> <span class="op">&lt;-</span> <span class="va">data_duplicated_values</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of duplicate value in data frame after calling distinct is'</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/duplicated.html">duplicated</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of duplicate value in data frame after calling distinct is0"</code></pre>
</div>
<div id="duplicates-based-on-specific-columns" class="section level3" number="22.5.2">
<h3>
<span class="header-section-number">22.5.2</span> Duplicates based on specific columns<a class="anchor" aria-label="anchor" href="#duplicates-based-on-specific-columns"><i class="fas fa-link"></i></a>
</h3>
<p>Some times duplication of elements in certain column/columns is not desirable. We want to be able to remove rows with duplication in specified columns. We first insert 5 rows with duplicates in “Day” and “Month”, we should see “158” rows after insertion:</p>
<div class="sourceCode" id="cb184"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of rows before adding 5 duplicated rows on Day and Month is'</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows before adding 5 duplicated rows on Day and Month is153"</code></pre>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span> <span class="fl">5</span><span class="op">)</span></span>
<span><span class="op">{</span></span>
<span>  <span class="va">Ozone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">50</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">Solor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">300</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">Wind</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">20</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="va">Temp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">20</span><span class="op">)</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">random_index</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, min <span class="op">=</span> <span class="fl">1</span>, max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">Month</span> <span class="op">&lt;-</span> <span class="va">data_duplicated_values</span><span class="op">[</span><span class="va">random_index</span>, <span class="st">'Month'</span><span class="op">]</span></span>
<span>  <span class="va">Day</span> <span class="op">&lt;-</span> <span class="va">data_duplicated_values</span><span class="op">[</span><span class="va">random_index</span>, <span class="st">'Day'</span><span class="op">]</span></span>
<span>  <span class="va">data_duplicated_values</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">+</span><span class="fl">1</span>,<span class="op">]</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">Ozone</span>, <span class="va">Solor</span>, <span class="va">Wind</span>, <span class="va">Temp</span>, <span class="va">Month</span>, <span class="va">Day</span><span class="op">)</span></span>
<span>  </span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of rows after adding 5 duplicated rows on Day and Month is'</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows after adding 5 duplicated rows on Day and Month is158"</code></pre>
<p>We can remove rows with duplicated “Day” and “Month” combination using “distinct()”. The “.keep_all = TRUE” argument makes sure that for each duplicated combination of Day and Month, we keep the first row for every duplicated combination and we keep all variables in the Data. We should observe the number of rows after dropping dupicated columns going back to “153”, which is the size of data frame before we insert rows with duplicated “Day” and “Month” combinations.</p>
<div class="sourceCode" id="cb188"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data_duplicated_values</span><span class="op">&lt;-</span> <span class="va">data_duplicated_values</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="va">Day</span>, <span class="va">Month</span>, .keep_all <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of rows after removing 5 duplicated rows on Dat and Month is'</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">data_duplicated_values</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows after removing 5 duplicated rows on Dat and Month is153"</code></pre>
</div>
</div>
<div id="missing-values" class="section level2" number="22.6">
<h2>
<span class="header-section-number">22.6</span> Missing Values<a class="anchor" aria-label="anchor" href="#missing-values"><i class="fas fa-link"></i></a>
</h2>
<p>Encountering missing data in dataset is not uncommon. When collecting temperature data the sensor might be broken and unable to measure temperature. When conduct public opinion surveying, the interviewee might forget filling entires on questionaires. Many data science job requires completeness of data, such as training predicative model based on numerical/categorical data. We will now discuss doing data cleaning in R.</p>
<div id="na-in-r" class="section level3" number="22.6.1">
<h3>
<span class="header-section-number">22.6.1</span> NA in R<a class="anchor" aria-label="anchor" href="#na-in-r"><i class="fas fa-link"></i></a>
</h3>
<p>In R, a missing value is represented by symbol “NA”.</p>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airquality</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     41     190  7.4   67     5   1
## 2     36     118  8.0   72     5   2
## 3     12     149 12.6   74     5   3
## 4     18     313 11.5   62     5   4
## 5     NA      NA 14.3   56     5   5
## 6     28      NA 14.9   66     5   6
## 7     23     299  8.6   65     5   7
## 8     19      99 13.8   59     5   8
## 9      8      19 20.1   61     5   9
## 10    NA     194  8.6   69     5  10</code></pre>
<p>We can observe, at index 5, the instance has missing value in “Ozone” and “Solar.R” feasure, represented by symbol “NA”.
### Dropping rows with missing data
A simple approach is to drop rows with missing data. If our task requires using all features in dataset, we can opt to drop all rows with at least one missing value. However, if our task required using some features, we only need to drop rows with missing values in feastures we specify. We will discuss both cases.
#### Drop all rows containing missing Data
Suppose we want to use all features in “airquality” dataset and we want to drop all rows with at least 1 missing values. We first check number of rows with missing data in the dataset. The ‘is.na(df)’ command returns a boolean array, where truth value at each index indicate if data element at the same index in data frame df is NA or not. By summing number of “TRUE” values in the ‘is.na(df)’, we know total number of missing values in the data set.</p>
<div class="sourceCode" id="cb192"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'total number of missing values is '</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "total number of missing values is 44"</code></pre>
<p>We see we have totally 44 missing with at least 1 missing values.
To know number of rows with missing value, we use “complete.cases(df)”. The return an array of boolean where boolean value at each index indicate if data instance/case at the corresponding row index in data frame df is complete (having no NA the missing value) or not. By summing the number of false in the array, we get the total number of rows that has at least 1 missing value.</p>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of rows with at least 1 missing value is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows with at least 1 missing value is 42"</code></pre>
<p>To visualize all rows with missing value, we can access them using the boolean array from “complete.cases()”. Due to large number of rows with missing value, we only put 10 here:</p>
<div class="sourceCode" id="cb196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">)</span>, <span class="op">]</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<p>We now remove rows with na. We use “drop_na()” function from tidyr library to remove all rows with missing values. There are multiple ways to drop rows with missing value, but we will not go exhaustive on this.</p>
<div class="sourceCode" id="cb197"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_na_droped</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of missing values after we drop all NA is "</span>,<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_na_droped</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values after we drop all NA is 0"</code></pre>
<div class="sourceCode" id="cb199"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of rows in data frame after extracting rows with NA is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_na_droped</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows in data frame after extracting rows with NA is 111"</code></pre>
<p>After removing all 42 rows with missing values, we only have 111 rows left, with 42 rows removed from total 153 rows in original data frame.</p>
<div id="drop-rows-with-missing-data-in-specified-columns" class="section level4" number="22.6.1.1">
<h4>
<span class="header-section-number">22.6.1.1</span> Drop rows with missing data in specified columns<a class="anchor" aria-label="anchor" href="#drop-rows-with-missing-data-in-specified-columns"><i class="fas fa-link"></i></a>
</h4>
<div id="na-in-single-column" class="section level5" number="22.6.1.1.1">
<h5>
<span class="header-section-number">22.6.1.1.1</span> NA in single column<a class="anchor" aria-label="anchor" href="#na-in-single-column"><i class="fas fa-link"></i></a>
</h5>
<p>We can see dropping all columns with missing data could be wasteful if we don’t use all features in the dataset. For example, if our job does not require feature “Ozone”, we don’t really care if “Ozone” value is missing or not as it is irrelevant to our task. We will explore how to drop rows with na in specific columns.</p>
<p>We see “is.na(df)” evaluate presence of NA(missing value) in the entire data set. If we change its argument from df, the entire data set, into a specific column, the function will only evaluate specific columns in the data set and return a boolean array that only reflects presence of missing value at the columns. For example, if we want to see number of rows with missing value in “Ozone” column:</p>
<div class="sourceCode" id="cb201"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of NA in Ozone column is '</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of NA in Ozone column is 37"</code></pre>
<p>There are 37 rows with NA in “Ozone” column. To drop rows with missing value in “Ozone”, we put column name “Ozone” as argument:</p>
<div class="sourceCode" id="cb203"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_na_droped_Ozone</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="va">Ozone</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_na_droped_Ozone</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 116</code></pre>
<p>37 rows are extracted from 153 columns, resulting in 116 rows.</p>
</div>
<div id="na-in-several-columns-and" class="section level5" number="22.6.1.1.2">
<h5>
<span class="header-section-number">22.6.1.1.2</span> NA in several columns (And)<a class="anchor" aria-label="anchor" href="#na-in-several-columns-and"><i class="fas fa-link"></i></a>
</h5>
<p>If we want to drop rows with NA in specific column, for example, rows with NA in both “Ozone” and “Solar.R” columns, we can take advantage of the fact that “is.na(df)” is a boolean array, and we can perform element wise boolean operation in two arrays of same dimension:</p>
<div class="sourceCode" id="cb205"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span> <span class="op">&amp;</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>We see number of rows with missing value in both “Ozone” and “Solar.R” is 2. We now visualize two rows:</p>
<div class="sourceCode" id="cb207"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_preProcessing</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span> <span class="op">&amp;</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span>, <span class="op">]</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 5     NA      NA 14.3   56     5   5
## 27    NA      NA  8.0   57     5  27</code></pre>
<p>Having the boolean array, we can negate the logics and obtain all rows where we don’t have missing values in “Ozone” and “Solar.R” at the same time.</p>
<div class="sourceCode" id="cb209"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_NA_Ozone_and_Solor</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span><span class="op">[</span><span class="op">!</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span> <span class="op">&amp;</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span>, <span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_NA_Ozone_and_Solor</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 151</code></pre>
<p>We have droped two rows from 153 rows in original dataset, so we have 151 rows left.</p>
</div>
<div id="na-in-several-columns-or" class="section level5" number="22.6.1.1.3">
<h5>
<span class="header-section-number">22.6.1.1.3</span> NA in several columns (Or)<a class="anchor" aria-label="anchor" href="#na-in-several-columns-or"><i class="fas fa-link"></i></a>
</h5>
<p>What if we want to drop columns with NA in “Ozone” or “Solar.R”, such that if any of the two columns contains missing values. We could have used boolean operation between several boolean arrays as we did, but it could be tedious as we have more feastures to consider. We could use “complete.cases()” but use specific columns in dataset as input. The “complete.cases()” returns false if a single column in the rows in data frame we pass in has a missing value, so we could perform “or” operation with it.</p>
<div class="sourceCode" id="cb211"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">!</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Ozone"</span>,<span class="st">"Solar.R"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 42</code></pre>
<p>There are 42 rows with missing values in either “Ozone” or “Solar.R”, or both. In fact, missing values only appear in those two columns, such that we get the total number of rows with missing values in the data set. We can obtain all datas that does not having missing value in “Ozone” or “Solar.R”.</p>
<div class="sourceCode" id="cb213"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_NA_Ozone_or_Solor</span><span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span><span class="op">[</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/complete.cases.html">complete.cases</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">[</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Ozone"</span>,<span class="st">"Solar.R"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span><span class="op">)</span>, <span class="op">]</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_NA_Ozone_or_Solor</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 111</code></pre>
<p>We have 111 rows after removing 42 rows with missing value on either “Ozone” or “Solar.R”</p>
<p>We can also use drop_na() to with columns specified in function arguement:</p>
<div class="sourceCode" id="cb215"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_NA_Ozone_or_Solor</span><span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Ozone"</span>, <span class="st">"Solar.R"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_NA_Ozone_or_Solor</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 111</code></pre>
</div>
<div id="drop-columns-with-certain-number-of-na" class="section level5" number="22.6.1.1.4">
<h5>
<span class="header-section-number">22.6.1.1.4</span> Drop columns with certain number of NA<a class="anchor" aria-label="anchor" href="#drop-columns-with-certain-number-of-na"><i class="fas fa-link"></i></a>
</h5>
<p>This might be uncommon, but we might want to drop rows with more than certain number of NA, such as rows with more than 3 NA and even rows with number of NA equal to number of columns, which means the row has all column value being NA. To know number of NA in each row, we can use “rowSums()” functions:</p>
<div class="sourceCode" id="cb217"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_preProcessing</span><span class="op">)</span><span class="op">)</span>,<span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  [1] 0 0 0 0 2 1 0 0 0 1</code></pre>
<p>This means for row 1 to row 10, row 5 has 2 NA and row 6 and 10 has 1 NA. We can drop all rows with number of NA above certain threshold. We now insert 3 rows with 3 NA into the data frame.</p>
<div class="sourceCode" id="cb219"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_3NA_Inserted</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="op">{</span></span>
<span>  <span class="va">Ozone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">50</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">Solor</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">300</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">Wind</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">20</span><span class="op">)</span>, <span class="fl">2</span><span class="op">)</span></span>
<span>  <span class="va">Temp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>,min <span class="op">=</span> <span class="fl">0</span>, max <span class="op">=</span> <span class="fl">20</span><span class="op">)</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">random_index</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, min <span class="op">=</span> <span class="fl">1</span>, max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_3NA_Inserted</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">Month</span> <span class="op">&lt;-</span> <span class="va">airQuality_3NA_Inserted</span> <span class="op">[</span><span class="va">random_index</span>, <span class="st">'Month'</span><span class="op">]</span></span>
<span>  <span class="va">Day</span> <span class="op">&lt;-</span> <span class="va">airQuality_3NA_Inserted</span> <span class="op">[</span><span class="va">random_index</span>, <span class="st">'Day'</span><span class="op">]</span></span>
<span>  </span>
<span>  </span>
<span>  <span class="va">toInsert</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">Ozone</span>, <span class="va">Solor</span>, <span class="va">Wind</span>, <span class="va">Temp</span>, <span class="va">Month</span>, <span class="va">Day</span><span class="op">)</span></span>
<span>  <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="va">random_index</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, min <span class="op">=</span> <span class="fl">1</span>, max <span class="op">=</span> <span class="fl">6</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">toInsert</span><span class="op">[</span><span class="va">random_index</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="va">random_index</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">floor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">1</span>, min <span class="op">=</span> <span class="fl">1</span>, max <span class="op">=</span> <span class="fl">6</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="va">toInsert</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/replace.html">replace</a></span><span class="op">(</span><span class="va">toInsert</span>, <span class="va">random_index</span>, <span class="cn">NA</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span></span>
<span>  <span class="va">airQuality_3NA_Inserted</span> <span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_3NA_Inserted</span> <span class="op">)</span><span class="op">+</span><span class="fl">1</span>,<span class="op">]</span> <span class="op">&lt;-</span> <span class="va">toInsert</span></span>
<span>  </span>
<span>  </span>
<span><span class="op">}</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">airQuality_3NA_Inserted</span>, <span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<pre><code>##     Ozone Solar.R Wind Temp Month Day
## 154     2      NA 2.96   15    NA  23
## 155    NA     103   NA   NA     9  29
## 156    NA      NA 9.43    4    NA   8</code></pre>
<div class="sourceCode" id="cb221"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">'number of rows in airQuality_3NA_Inserted is'</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_3NA_Inserted</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows in airQuality_3NA_Inserted is 156"</code></pre>
<p>Now last 3 rows have 3 NA at tail of airQuality_3NA_Inserted. We now check number of rows with more than or equal to 3 NA:</p>
<div class="sourceCode" id="cb223"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of rows with at least 3 NA in airQuality_3NA_Inserted is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_3NA_Inserted</span><span class="op">)</span><span class="op">)</span> <span class="op">&gt;=</span> <span class="fl">3</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows with at least 3 NA in airQuality_3NA_Inserted is 2"</code></pre>
<p>Now we have 3 rows with at least 3 NA. We now drop rows with at least 3 NA from airQuality_3NA_Inserted by selecting rows with NA less than 3 and reset reference of airQuality_3NA_Inserted:</p>
<div class="sourceCode" id="cb225"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_3NA_Inserted</span> <span class="op">&lt;-</span> <span class="va">airQuality_3NA_Inserted</span><span class="op">[</span><span class="op">!</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">rowSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_3NA_Inserted</span><span class="op">)</span><span class="op">)</span> <span class="op">&gt;=</span> <span class="fl">3</span><span class="op">)</span>, <span class="op">]</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of rows in airQuality_3NA_Inserted after dropping is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">airQuality_3NA_Inserted</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of rows in airQuality_3NA_Inserted after dropping is 154"</code></pre>
<p>We have drop all 3 rows with at least 3 NA, so the size of airQuality_3NA_Inserted drops from 156 to 153.</p>
</div>
</div>
</div>
<div id="impute" class="section level3" number="22.6.2">
<h3>
<span class="header-section-number">22.6.2</span> Impute<a class="anchor" aria-label="anchor" href="#impute"><i class="fas fa-link"></i></a>
</h3>
<p>Dropping rows is a straight forward approach. However, dropping too many drows would induce huge data loss, which would be detrimental to our task. We can insert values we specify into entries with missing values. This will minimize data loss. Though we would never know if imputed values could reflect the true pattern of the data.</p>
<div id="impute-numerical-values" class="section level4" number="22.6.2.1">
<h4>
<span class="header-section-number">22.6.2.1</span> Impute numerical values<a class="anchor" aria-label="anchor" href="#impute-numerical-values"><i class="fas fa-link"></i></a>
</h4>
<div id="impute-with-constant" class="section level5" number="22.6.2.1.1">
<h5>
<span class="header-section-number">22.6.2.1.1</span> Impute with constant<a class="anchor" aria-label="anchor" href="#impute-with-constant"><i class="fas fa-link"></i></a>
</h5>
<p>For a column with missing value,we select a constant we think will reflect the real data and fill missing entry in the column with the constant we have selected.</p>
<p>Let’s say we use constant 30 to fill “Ozone” entries with missing values.</p>
<div class="sourceCode" id="cb227"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_const_filled</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of missing values in Ozone column is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_const_filled</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Ozone column is 37"</code></pre>
<div class="sourceCode" id="cb229"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_const_filled</span> , <span class="fl">5</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    NA      NA 14.3   56     5   5</code></pre>
<p>We now fill:</p>
<div class="sourceCode" id="cb231"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_const_filled</span><span class="op">$</span><span class="va">Ozone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://SteffenMoritz.github.io/imputeTS/reference/na_replace.html">na_replace</a></span><span class="op">(</span><span class="va">airQuality_const_filled</span><span class="op">$</span><span class="va">Ozone</span>, fill <span class="op">=</span> <span class="fl">30</span>, maxgap <span class="op">=</span> <span class="cn">Inf</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of missing values in Ozone column is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_const_filled</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Ozone column is 0"</code></pre>
<div class="sourceCode" id="cb233"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_const_filled</span> , <span class="fl">5</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   Ozone Solar.R Wind Temp Month Day
## 1    41     190  7.4   67     5   1
## 2    36     118  8.0   72     5   2
## 3    12     149 12.6   74     5   3
## 4    18     313 11.5   62     5   4
## 5    30      NA 14.3   56     5   5</code></pre>
<p>We see NA in Ozone column of row 5 is imputed by constant 30.</p>
<ul>
<li>Pro
<ul>
<li>Easy to understand.</li>
</ul>
</li>
<li>Con
<ul>
<li>Value assigned by human intuition is too arbitrary and might be unrealistic.</li>
</ul>
</li>
</ul>
</div>
<div id="impute-with-sample-statistics" class="section level5" number="22.6.2.1.2">
<h5>
<span class="header-section-number">22.6.2.1.2</span> Impute with Sample statistics<a class="anchor" aria-label="anchor" href="#impute-with-sample-statistics"><i class="fas fa-link"></i></a>
</h5>
<p>We can impute missing values in a column using sample statistics of the columns such as mean and median. This way we fill the missing value and does not alter data statistics in the column. We now fill “Ozone” column with current “Mean” of “Ozone” column and “Solar.R” with median of “Solar.R” column. Note the “na.rm = True” arguement is to neglect missing value when computing sample statistics so that we get a real value answer.</p>
<div class="sourceCode" id="cb235"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_sstat_impute</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Mean of Ozone before impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Ozone</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "Mean of Ozone before impute is 42.1293103448276"</code></pre>
<div class="sourceCode" id="cb237"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Median of Solar.R before impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Solar.R</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "Median of Solar.R before impute is 205"</code></pre>
<div class="sourceCode" id="cb239"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of missing values in Ozone column before impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Ozone column before impute is 37"</code></pre>
<div class="sourceCode" id="cb241"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of missing values in Solar.R column before impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Solar.R column before impute is 7"</code></pre>
<div class="sourceCode" id="cb243"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Ozone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://SteffenMoritz.github.io/imputeTS/reference/na_mean.html">na_mean</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Ozone</span>, option <span class="op">=</span> <span class="st">"mean"</span>, maxgap <span class="op">=</span> <span class="cn">Inf</span><span class="op">)</span></span>
<span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Solar.R</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://SteffenMoritz.github.io/imputeTS/reference/na_mean.html">na_mean</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Solar</span>, option <span class="op">=</span> <span class="st">"median"</span>, maxgap <span class="op">=</span> <span class="cn">Inf</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Mean of Ozone after impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "Mean of Ozone after impute is 42.1293103448276"</code></pre>
<div class="sourceCode" id="cb245"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Median of Solar.R after impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/stats/median.html">median</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "Median of Solar.R after impute is 205"</code></pre>
<div class="sourceCode" id="cb247"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of missing values in Ozone column after impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Ozone column after impute is 0"</code></pre>
<div class="sourceCode" id="cb249"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"number of missing values in Solar.R column after impute is "</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_sstat_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Solar.R column after impute is 0"</code></pre>
<p>We see we no longer have missing values in both columns and mean in “Ozone” column and median in “Solar.R” are both unchanging from before the impute.</p>
<ul>
<li>Pro
<ul>
<li>Easy to understand.</li>
<li>Does not change sample statistics</li>
</ul>
</li>
<li>Con
<ul>
<li>Maybe the distribution of valid values in columns are skewed to left or right or have many outliers such that sample statistics do not reflect actual pattern of data</li>
</ul>
</li>
</ul>
</div>
<div id="impute-by-value-adjacent-to-missing-value" class="section level5" number="22.6.2.1.3">
<h5>
<span class="header-section-number">22.6.2.1.3</span> Impute by value adjacent to Missing value<a class="anchor" aria-label="anchor" href="#impute-by-value-adjacent-to-missing-value"><i class="fas fa-link"></i></a>
</h5>
<p>Often in time-series data, value on a time point is highly assosicated with most adjacent valid values. Therefore, we want to fill a missing entries using valid data values before or after it.</p>
<div class="sourceCode" id="cb251"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_Adjacent_impute</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_Adjacent_impute</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     41     190  7.4   67     5   1
## 2     36     118  8.0   72     5   2
## 3     12     149 12.6   74     5   3
## 4     18     313 11.5   62     5   4
## 5     NA      NA 14.3   56     5   5
## 6     28      NA 14.9   66     5   6
## 7     23     299  8.6   65     5   7
## 8     19      99 13.8   59     5   8
## 9      8      19 20.1   61     5   9
## 10    NA     194  8.6   69     5  10</code></pre>
<p>We first fill missing values in Ozone column with last observed valid value:</p>
<div class="sourceCode" id="cb253"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_Adjacent_impute</span><span class="op">$</span><span class="va">Ozone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://SteffenMoritz.github.io/imputeTS/reference/na_locf.html">na_locf</a></span><span class="op">(</span><span class="va">airQuality_Adjacent_impute</span><span class="op">$</span><span class="va">Ozone</span>, option <span class="op">=</span> <span class="st">"locf"</span><span class="op">)</span></span></code></pre></div>
<p>We then fill missing values in Solar.R column with next observed valid value</p>
<div class="sourceCode" id="cb254"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_Adjacent_impute</span><span class="op">$</span><span class="va">Solar.R</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://SteffenMoritz.github.io/imputeTS/reference/na_locf.html">na_locf</a></span><span class="op">(</span><span class="va">airQuality_Adjacent_impute</span><span class="op">$</span><span class="va">Solar.R</span>, option <span class="op">=</span> <span class="st">"nocb"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_Adjacent_impute</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     41     190  7.4   67     5   1
## 2     36     118  8.0   72     5   2
## 3     12     149 12.6   74     5   3
## 4     18     313 11.5   62     5   4
## 5     18     299 14.3   56     5   5
## 6     28     299 14.9   66     5   6
## 7     23     299  8.6   65     5   7
## 8     19      99 13.8   59     5   8
## 9      8      19 20.1   61     5   9
## 10     8     194  8.6   69     5  10</code></pre>
<p>If we have missing value at beginning or end of data frame, which is rare, we can remedy using “na_remaining” argument in “na_locf()” to handle remaining missing value after filling. More details can be found in imputeTS documentation.</p>
<ul>
<li>Pro
<ul>
<li>For time series data, using adjacent value that are close could capture time dependent pattern</li>
</ul>
</li>
<li>Con
<ul>
<li>If cloested adjacent value is too far away, filling adjacent value would not sustain time dependent pattern.</li>
</ul>
</li>
</ul>
</div>
<div id="impute-using-predicative-model" class="section level5" number="22.6.2.1.4">
<h5>
<span class="header-section-number">22.6.2.1.4</span> Impute using predicative model<a class="anchor" aria-label="anchor" href="#impute-using-predicative-model"><i class="fas fa-link"></i></a>
</h5>
<p>If we believe certain features in the data frame depends on some other features, we can use other features to fit a predicative model to predict missing value in certain feature. We need to make sure the “other features” our prediction is based on are all valid entries, which we need to impute using some method. We now assume “Ozone” and “Solar.R” features depends on climate related features such as “Wind” and “Temperature”, and we build linear regression models for “Ozone” and “Solar.R” based on “Wind” and “Temperature”.</p>
<div class="sourceCode" id="cb256"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_lm_impute</span> <span class="op">&lt;-</span> <span class="va">airQuality_preProcessing</span></span>
<span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     41     190  7.4   67     5   1
## 2     36     118  8.0   72     5   2
## 3     12     149 12.6   74     5   3
## 4     18     313 11.5   62     5   4
## 5     NA      NA 14.3   56     5   5
## 6     28      NA 14.9   66     5   6
## 7     23     299  8.6   65     5   7
## 8     19      99 13.8   59     5   8
## 9      8      19 20.1   61     5   9
## 10    NA     194  8.6   69     5  10</code></pre>
<div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of missing values in Ozone column before impute is '</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Ozone column before impute is 37"</code></pre>
<div class="sourceCode" id="cb260"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of missing values in Solar.R column before impute is '</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Solar.R column before impute is 7"</code></pre>
<div class="sourceCode" id="cb262"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">linear_model_Ozone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Ozone</span> <span class="op">~</span> <span class="va">Wind</span> <span class="op">+</span> <span class="va">Temp</span>, data <span class="op">=</span> <span class="va">airQuality_lm_impute</span><span class="op">)</span></span>
<span><span class="va">linear_model_Solar.R</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Solar.R</span> <span class="op">~</span> <span class="va">Wind</span> <span class="op">+</span> <span class="va">Temp</span>, data <span class="op">=</span> <span class="va">airQuality_lm_impute</span><span class="op">)</span></span>
<span></span>
<span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">linear_model_Ozone</span>, </span>
<span>                                                                         newdata <span class="op">=</span> <span class="va">airQuality_lm_impute</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Wind'</span>, <span class="st">'Temp'</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">linear_model_Solar.R</span>, </span>
<span>                                                                         newdata <span class="op">=</span> <span class="va">airQuality_lm_impute</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">'Wind'</span>, <span class="st">'Temp'</span><span class="op">)</span><span class="op">]</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##        Ozone  Solar.R Wind Temp Month Day
## 1   41.00000 190.0000  7.4   67     5   1
## 2   36.00000 118.0000  8.0   72     5   2
## 3   12.00000 149.0000 12.6   74     5   3
## 4   18.00000 313.0000 11.5   62     5   4
## 5  -11.67673 127.4317 14.3   56     5   5
## 6   28.00000 159.5042 14.9   66     5   6
## 7   23.00000 299.0000  8.6   65     5   7
## 8   19.00000  99.0000 13.8   59     5   8
## 9    8.00000  19.0000 20.1   61     5   9
## 10  29.66190 194.0000  8.6   69     5  10</code></pre>
<p>Since the original data are integer, We now convert “Ozone” and “Solar.R” back to integer from double.</p>
<div class="sourceCode" id="cb264"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Ozone</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span></span>
<span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Solar.R</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">as.integer</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    Ozone Solar.R Wind Temp Month Day
## 1     41     190  7.4   67     5   1
## 2     36     118  8.0   72     5   2
## 3     12     149 12.6   74     5   3
## 4     18     313 11.5   62     5   4
## 5    -11     127 14.3   56     5   5
## 6     28     159 14.9   66     5   6
## 7     23     299  8.6   65     5   7
## 8     19      99 13.8   59     5   8
## 9      8      19 20.1   61     5   9
## 10    29     194  8.6   69     5  10</code></pre>
<div class="sourceCode" id="cb266"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">linear_model_Ozone</span> </span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Ozone ~ Wind + Temp, data = airQuality_lm_impute)
## 
## Coefficients:
## (Intercept)         Wind         Temp  
##     -71.033       -3.055        1.840</code></pre>
<div class="sourceCode" id="cb268"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">linear_model_Solar.R</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Solar.R ~ Wind + Temp, data = airQuality_lm_impute)
## 
## Coefficients:
## (Intercept)         Wind         Temp  
##     -76.362        2.211        3.075</code></pre>
<p>We have now filled missing values using linear regresison model prediction from valid values from other columns.</p>
<div class="sourceCode" id="cb270"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of missing values in Ozone column after impute is '</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Ozone</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Ozone column after impute is 0"</code></pre>
<div class="sourceCode" id="cb272"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">'number of missing values in Solar.R column after impute is '</span>, <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">airQuality_lm_impute</span><span class="op">$</span><span class="va">Solar.R</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "number of missing values in Solar.R column after impute is 0"</code></pre>
<ul>
<li>Pro
<ul>
<li>If the feature predict indeed depend on other features of the data set, the missing value will be replace by values that reflect the true pattern.</li>
</ul>
</li>
<li>Con
<ul>
<li>Depending on what predicative model we use, the training and prediction could be computationally expensive.</li>
<li>If the feature we predict does not depend on other features in data set we select to construct predicative model, the filled missing value will be mis leading for our future analysis.</li>
</ul>
</li>
</ul>
</div>
</div>
<div id="impute-categorical-features" class="section level4" number="22.6.2.2">
<h4>
<span class="header-section-number">22.6.2.2</span> Impute categorical features<a class="anchor" aria-label="anchor" href="#impute-categorical-features"><i class="fas fa-link"></i></a>
</h4>
<p>As for imputing categorical features,</p>
<p>Replacing NA in categorical features with string</p>
<div class="sourceCode" id="cb274"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">na_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>A <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="cn">NA</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">5</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>                     B <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">10</span>, <span class="cn">NA</span>, <span class="fl">7</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>                    fantasy <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sad"</span>, <span class="st">"we"</span>, <span class="cn">NA</span>, <span class="st">'adf'</span>, <span class="st">'NA'</span><span class="op">)</span>,</span>
<span>                     C <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="cn">NA</span>, <span class="fl">9</span>, <span class="cn">NA</span><span class="op">)</span>, </span>
<span>                     D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"tangro"</span>, <span class="st">"ok"</span>, <span class="cn">NA</span>, <span class="st">'yes'</span>, <span class="st">'NA'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">i1</span> <span class="op">&lt;-</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">na_df</span>, <span class="va">is.numeric</span><span class="op">)</span></span>
<span></span>
<span><span class="va">na_df</span><span class="op">[</span><span class="va">i1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">na_df</span><span class="op">[</span><span class="va">i1</span><span class="op">]</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span>              <span class="fu"><a href="https://rdrr.io/r/base/replace.html">replace</a></span><span class="op">(</span><span class="va">x</span>, <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, <span class="st">'MISSING'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">na_df</span></span></code></pre></div>
<pre><code>##    A  B fantasy  C       D
## 1 NA  4     sad  1  tangro
## 2  7 10      we  0      ok
## 3  8 NA MISSING NA MISSING
## 4  5  7     adf  9     yes
## 5  3  4      NA NA      NA</code></pre>
<p>Replacing NA in categorical features with mode <strong>[1]</strong></p>
<div class="sourceCode" id="cb276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">na_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>A <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="cn">NA</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">5</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>                     B <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">10</span>, <span class="cn">NA</span>, <span class="fl">7</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>                    fantasy <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sad"</span>, <span class="st">"we"</span>, <span class="cn">NA</span>, <span class="st">'adf'</span>, <span class="st">'NA'</span><span class="op">)</span>,</span>
<span>                     C <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="cn">NA</span>, <span class="fl">9</span>, <span class="cn">NA</span><span class="op">)</span>, </span>
<span>                     D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"tangro"</span>, <span class="st">"ok"</span>, <span class="cn">NA</span>, <span class="st">'yes'</span>, <span class="st">'NA'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">i1</span> <span class="op">&lt;-</span> <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span><span class="op">(</span><span class="va">na_df</span>, <span class="va">is.numeric</span><span class="op">)</span></span>
<span><span class="va">Mode</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span> <span class="op">{</span> </span>
<span>      <span class="va">ux</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span></span>
<span>      <span class="va">ux</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.min.html">which.max</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/tabulate.html">tabulate</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">ux</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">]</span> </span>
<span><span class="op">}</span></span>
<span><span class="va">na_df</span><span class="op">[</span><span class="va">i1</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span><span class="op">(</span><span class="va">na_df</span><span class="op">[</span><span class="va">i1</span><span class="op">]</span>, <span class="kw">function</span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span>              <span class="fu"><a href="https://rdrr.io/r/base/replace.html">replace</a></span><span class="op">(</span><span class="va">x</span>, <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span>, <span class="fu">Mode</span><span class="op">(</span><span class="va">x</span><span class="op">[</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">]</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">na_df</span></span></code></pre></div>
<pre><code>##    A  B fantasy  C      D
## 1 NA  4     sad  1 tangro
## 2  7 10      we  0     ok
## 3  8 NA     adf NA     NA
## 4  5  7     adf  9    yes
## 5  3  4      NA NA     NA</code></pre>
</div>
</div>
</div>
<div id="data-scaling" class="section level2" number="22.7">
<h2>
<span class="header-section-number">22.7</span> Data scaling<a class="anchor" aria-label="anchor" href="#data-scaling"><i class="fas fa-link"></i></a>
</h2>
<p>Scaling is important for data analysis and exploration, Data without scaling can produce misleading result. Also scaling is beneficial for mathematics computation and machine learning.</p>
<div id="standardization" class="section level3" number="22.7.1">
<h3>
<span class="header-section-number">22.7.1</span> standardization<a class="anchor" aria-label="anchor" href="#standardization"><i class="fas fa-link"></i></a>
</h3>
<p>Standardization unify all the samples’ mean and std to 0 and 1, so we could compare the distribution among the scaled samples.</p>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># we can use the scale from dplyr</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://openintrostat.github.io/openintro/">openintro</a></span><span class="op">)</span></span>
<span><span class="va">scale_df</span> <span class="op">=</span> <span class="va">duke_forest_copy</span><span class="op">[</span>, <span class="fl">2</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span></span>
<span><span class="co"># what happen if we did not scale.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">scale_df</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="r_data_cleaning_files/figure-html/unnamed-chunk-58-1.png" width="80%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb279"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># after scaling</span></span>
<span><span class="va">scale_df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_all</a></span><span class="op">(</span><span class="op">~</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/scale.html">scale</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="va">as.vector</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># apply scale() to every column</span></span></code></pre></div>
<div class="inline-figure"><img src="r_data_cleaning_files/figure-html/unnamed-chunk-58-2.png" width="80%" style="display: block; margin: auto;"></div>
</div>
<div id="min-max-scaling" class="section level3" number="22.7.2">
<h3>
<span class="header-section-number">22.7.2</span> Min Max scaling<a class="anchor" aria-label="anchor" href="#min-max-scaling"><i class="fas fa-link"></i></a>
</h3>
<p>MINMAX scaling is good for svm, so don’t hesistate to use it :)</p>
<div class="sourceCode" id="cb280"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">minmax</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">na.rm</span> <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="op">(</span><span class="va">x</span><span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="op">/</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">-</span><span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="va">scale_df</span> <span class="op">=</span> <span class="va">duke_forest_copy</span><span class="op">[</span>, <span class="fl">2</span><span class="op">:</span><span class="fl">5</span><span class="op">]</span></span>
<span><span class="co"># what happen if we did not scale.</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="va">scale_df</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="r_data_cleaning_files/figure-html/unnamed-chunk-59-1.png" width="80%" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">scale_df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate_all.html">mutate_all</a></span><span class="op">(</span><span class="op">~</span><span class="op">(</span><span class="fu">minmax</span><span class="op">(</span><span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="va">as.vector</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/graphics/boxplot.html">boxplot</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># apply minmax() to every column</span></span></code></pre></div>
<div class="inline-figure"><img src="r_data_cleaning_files/figure-html/unnamed-chunk-59-2.png" width="80%" style="display: block; margin: auto;"></div>
</div>
</div>
<div id="data-encoding" class="section level2" number="22.8">
<h2>
<span class="header-section-number">22.8</span> data encoding<a class="anchor" aria-label="anchor" href="#data-encoding"><i class="fas fa-link"></i></a>
</h2>
<div id="ordinal-encoding" class="section level3" number="22.8.1">
<h3>
<span class="header-section-number">22.8.1</span> ordinal encoding<a class="anchor" aria-label="anchor" href="#ordinal-encoding"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb282"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ordinal</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">x</span>, <span class="va">order</span><span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">x</span>, levels <span class="op">=</span> <span class="va">order</span>, exclude <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">x</span></span>
<span><span class="op">}</span></span>
<span><span class="va">encode_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>A <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">5</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>                     B <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">10</span>, <span class="cn">NA</span>, <span class="fl">7</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>                    fantasy <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sad"</span>, <span class="st">"we"</span>, <span class="cn">NA</span>, <span class="st">'adf'</span>, <span class="st">'NA'</span><span class="op">)</span>,</span>
<span>                     C <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="cn">NA</span>, <span class="fl">9</span>, <span class="cn">NA</span><span class="op">)</span>, </span>
<span>                     D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"tangro"</span>, <span class="st">"ok"</span>, <span class="st">'NA'</span>, <span class="st">'yes'</span>, <span class="st">'NA'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="st">'origin:'</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "origin:"</code></pre>
<div class="sourceCode" id="cb284"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">encode_df</span><span class="op">[</span><span class="st">"D"</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>## $D
## [1] "tangro" "ok"     "NA"     "yes"    "NA"</code></pre>
<div class="sourceCode" id="cb286"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="st">'encoded:'</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "encoded:"</code></pre>
<div class="sourceCode" id="cb288"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">ordinal</span><span class="op">(</span><span class="va">encode_df</span><span class="op">[[</span><span class="st">"D"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 1 2 3 4 3</code></pre>
</div>
<div id="one-hot-encoding-3" class="section level3" number="22.8.2">
<h3>
<span class="header-section-number">22.8.2</span> one-hot encoding <strong>[3]</strong><a class="anchor" aria-label="anchor" href="#one-hot-encoding-3"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb290"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">encode_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>A <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">7</span>, <span class="fl">8</span>, <span class="fl">5</span>, <span class="fl">3</span><span class="op">)</span>,</span>
<span>                     B <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">10</span>, <span class="cn">NA</span>, <span class="fl">7</span>, <span class="fl">4</span><span class="op">)</span>, </span>
<span>                    fantasy <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"sad"</span>, <span class="st">"we"</span>, <span class="st">"seaweed"</span>, <span class="st">'adf'</span>, <span class="st">'NA'</span><span class="op">)</span>,</span>
<span>                     C <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="cn">NA</span>, <span class="fl">9</span>, <span class="cn">NA</span><span class="op">)</span>, </span>
<span>                     D <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"tangro"</span>, <span class="st">"ok"</span>, <span class="st">'NA'</span>, <span class="st">'yes'</span>, <span class="st">'NA'</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">dummy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/caret/man/dummyVars.html">dummyVars</a></span><span class="op">(</span><span class="st">" ~ ."</span>, data<span class="op">=</span><span class="va">encode_df</span><span class="op">)</span></span>
<span><span class="va">newdata</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">dummy</span>, newdata <span class="op">=</span> <span class="va">encode_df</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">newdata</span></span></code></pre></div>
<pre><code>##   A  B fantasyadf fantasyNA fantasysad fantasyseaweed fantasywe  C DNA Dok
## 1 1  4          0         0          1              0         0  1   0   0
## 2 7 10          0         0          0              0         1  0   0   1
## 3 8 NA          0         0          0              1         0 NA   1   0
## 4 5  7          1         0          0              0         0  9   0   0
## 5 3  4          0         1          0              0         0 NA   1   0
##   Dtangro Dyes
## 1       1    0
## 2       0    0
## 3       0    0
## 4       0    1
## 5       0    0</code></pre>
</div>
</div>
<div id="reference" class="section level2" number="22.9">
<h2>
<span class="header-section-number">22.9</span> Reference<a class="anchor" aria-label="anchor" href="#reference"><i class="fas fa-link"></i></a>
</h2>
<p>[1] <a href="https://sparkbyexamples.com/r-programming/how-to-do-left-join-in-r/#" class="uri">https://sparkbyexamples.com/r-programming/how-to-do-left-join-in-r/#</a>:~:text=How%20to%20do%20left%20join%20on%20data%20frames%20in%20R,join%20data%20frames%20in%20R.</p>
<p>[2]<a href="https://stackoverflow.com/questions/36377813/impute-most-frequent-categorical-value-in-all-columns-in-data-frame" class="uri">https://stackoverflow.com/questions/36377813/impute-most-frequent-categorical-value-in-all-columns-in-data-frame</a></p>
<p>[3] <a href="https://datatricks.co.uk/one-hot-encoding-in-r-three-simple-methods" class="uri">https://datatricks.co.uk/one-hot-encoding-in-r-three-simple-methods</a></p>

</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="tutorial-for-vector-fields-in-r.html"><span class="header-section-number">21</span> Tutorial for vector fields in r</a></div>
<div class="next"><a href="introduction-to-shiny-web-apps.html"><span class="header-section-number">23</span> Introduction to Shiny Web Apps</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#data-cleaning-with-r"><span class="header-section-number">22</span> Data cleaning with r</a></li>
<li><a class="nav-link" href="#data-cleaning-with-r-1"><span class="header-section-number">22.1</span> Data cleaning with R</a></li>
<li><a class="nav-link" href="#import-data-set"><span class="header-section-number">22.2</span> Import data set</a></li>
<li><a class="nav-link" href="#introduction"><span class="header-section-number">22.3</span> Introduction</a></li>
<li>
<a class="nav-link" href="#data-frame-modification-general-modification"><span class="header-section-number">22.4</span> Data frame modification (general modification)</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#create-dataframe-by-arrays"><span class="header-section-number">22.4.1</span> Create DataFrame by arrays</a></li>
<li><a class="nav-link" href="#create-dataframe-by-combining-two-dataframeusing-cbindrbind"><span class="header-section-number">22.4.2</span> Create DataFrame by combining two dataFrame(using cbind/rbind)</a></li>
<li><a class="nav-link" href="#addingchange-row-name"><span class="header-section-number">22.4.3</span> adding/change row name</a></li>
<li><a class="nav-link" href="#changing-column-names"><span class="header-section-number">22.4.4</span> changing column names</a></li>
<li><a class="nav-link" href="#adding-array-to-to-dataframe-as-new-column"><span class="header-section-number">22.4.5</span> Adding array to to dataFrame as new column</a></li>
<li><a class="nav-link" href="#adding-column-by-combination-of-other-columns"><span class="header-section-number">22.4.6</span> adding column by combination of other columns</a></li>
<li><a class="nav-link" href="#joining-two-table-2"><span class="header-section-number">22.4.7</span> joining two table [2]</a></li>
<li><a class="nav-link" href="#pivoting-dataframe-understanding-pivot_longer"><span class="header-section-number">22.4.8</span> pivoting dataframe, understanding pivot_longer</a></li>
<li><a class="nav-link" href="#ordering"><span class="header-section-number">22.4.9</span> ordering</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#duplicated-values"><span class="header-section-number">22.5</span> Duplicated Values</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#data-set-with-row-wise-duplicates"><span class="header-section-number">22.5.1</span> Data set with row-wise duplicates</a></li>
<li><a class="nav-link" href="#duplicates-based-on-specific-columns"><span class="header-section-number">22.5.2</span> Duplicates based on specific columns</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#missing-values"><span class="header-section-number">22.6</span> Missing Values</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#na-in-r"><span class="header-section-number">22.6.1</span> NA in R</a></li>
<li><a class="nav-link" href="#impute"><span class="header-section-number">22.6.2</span> Impute</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#data-scaling"><span class="header-section-number">22.7</span> Data scaling</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#standardization"><span class="header-section-number">22.7.1</span> standardization</a></li>
<li><a class="nav-link" href="#min-max-scaling"><span class="header-section-number">22.7.2</span> Min Max scaling</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#data-encoding"><span class="header-section-number">22.8</span> data encoding</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#ordinal-encoding"><span class="header-section-number">22.8.1</span> ordinal encoding</a></li>
<li><a class="nav-link" href="#one-hot-encoding-3"><span class="header-section-number">22.8.2</span> one-hot encoding [3]</a></li>
</ul>
</li>
<li><a class="nav-link" href="#reference"><span class="header-section-number">22.9</span> Reference</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/jtr13/cc22tt/blob/main/r_data_cleaning.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/jtr13/cc22tt/edit/main/r_data_cleaning.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Community Contributions for EDAV Fall 2022 Tues/Thurs</strong>" was written by . It was last built on 2022-11-15.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
