# Model evaluation, selection & visualization with easystats

Zhuolin Luo (zl2852), Kaiyuan Liu (kl3447)

We created a cheat sheet for the package named easystats in R. easystats in a collective framework of packages, including "performance", "parameters", etc. It intends for easier statistical modeling, reporting, and visualization. 

This cheat sheet will focus on the functions, examples, and visualizations related to reporting, checking, and visualizing model parameters, model predictions, model assumptions, model performance, and model selection with easystats package. Hopefully it can smoothen the model building process. The cheat sheet is divided into following parts:

Parameters: this section includes functions reporting the features of parameters in a model. 

Predictions: this section includes functions making model-based estimations and predictions, with visualization examples provided.

Assumption Diagnostics: this section includes functions testing whether a model satisfies a specific assumption and returning the corresponding value, with visualization examples provided.

Performance: this section includes functions that report the metrics evaluating a model's performance.

Model Selection: this section includes functions that compares the performance among different models and helps select the model, with visualization examples provided. 

The cheatsheet is available here: [Cheat Sheet for Model Evaluation, Selection & Visualization with easystats] (https://github.com/ChristalL99/Fall_2022_5702_EDAV_Community_Contribution/blob/17c60a9ddf50770303bc7d9b12ff308cd13a6370/Cheatsheet%20for%20Model%20Evaluation,%20Selection%20&%20Visualization%20with%20easystats.pdf)