
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Git and version control

Dianjing Fan and Yijia He

Version control is one of the most essential techniques for programmers.  Version control and Git are helpful for programmers and software teams to manage the changes in the codes over time. It allows the developers to collaboratively work faster, smarter, and more efficiently while reducing development time and communication costs. It can keep track of every modification of the codes by each contributor without conflicting with the concurrent work. In addition, the knowledge and practice of version control and Git are usually required for programmers in a workplace setting. At the same time, they are not well taught in school courses and are not explicitly mentioned in the job description in most cases. Therefore, we create a cheat sheet of Git for beginners to learn and understand Git within a short time. Through this project, we gained a deeper understanding of version control and Git in terms of why we use Git, its terminology, and so on, and practiced the must-know commands used in Git. We might add more real-world examples of using Git commands, record a short tutorial video for beginners, or include the knowledge of Github next time.

You can find the cheatsheet here:
https://github.com/BrownSugarBobaMilkTea/edav_git_cheatsheet/blob/main/git_cheatsheet.pdf
