# Helpful ggplot2 Extensions Cheatsheet

Frank Li and Liang Zhuang

Currently, there are a total of 117 ggplot2 extensions and those extensions add additional features to ggplot2 and make it more powerful. This cheatsheet includes useful information for four of the ggplot2 extensions: ggbump, ggradar, ggpol, and treemapify.

ggbump: it creates varies bump charts in ggplot. Bump charts are good to plot the path between nodes that have no statistical significance.

ggradar: it creates radar charts. Radar charts are useful for data values with multiple common variables and is widely used for performance analysis.

ggpol: it adds additional features to ggplot2 including GeomArcbar, GeomParliament, GeomCircle, GeomTshignlight, FacetShare, GeomBartext, and GeomBoxjitter. More details here: <https://erocoar.github.io/ggpol/>.

treemapify: it creates tree maps in ggplot2. It is useful for
data with hierarchy, such as country GDP and company’s stock market share.

for more extensions, use this link: <https://exts.ggplot2.tidyverse.org/gallery/>

The cheatsheet is available here: <https://github.com/leolisticierism/EDAV_Community_Contribution/blob/main/EDAV%20Community%20Contribution%20Cheat%20Sheet.pdf>
