# Different ways to create world map in R

Yuhang Qiu and Yinqi Wang

## Explanation of Motivation
Plotting a world map is a good visualization strategy if someone wants to analyze the data country by country, or even continent by continent. Using a world map also helps us in terms of visualizing locations and distances (between countries, cities, etc.). Making a world map would also be good for geographic researches. Some examples to use a world map are: Gini around the world, and what countries are developed and undeveloped. There are a lot of topics that the world map can visualize. In this community contribution project, we've learned to make a world map (in different style and ways) using multiple packages such as "rnaturalearth" and "rworldmap" and got a refreshing and thorough understanding of those packages and methods. What we might do differently next time is trying to record a video tutorial on the packages and methods we've introduced and discussed in this cheatsheet.  
  
The link to our cheat sheet is:  
[https://github.com/a844574798/worldMapCheatSheet/blob/main/WorldMapCheatsheet.pdf](https://github.com/a844574798/worldMapCheatSheet/blob/main/WorldMapCheatsheet.pdf)






